### PR TITLE
Make plot_layout and plot_counts look a little better in vignettes

### PR DESCRIPTION
**Pull request by ZetrextJG**
Before:
image

After:
image
image

This is still not a perfect solution as it is dependent on the device aspect ration to some extend, but it will be better looking in vignettes and everyday usage

### CODE REVIEW

**Review by Fersoil — CHANGES_REQUESTED** [review]
for me the layout apperance hasn't improved:
image
how have you fixed the area value?

**Comment by nizwant** [comment]
I think I came up with a solution that will work no matter where it's displayed, and it doesn't rely on `dev.size`. First, you generate a plot and save it in high resolution as a jpeg. Then you read the static images, and all issues with scaling are gone.

**Comment by Fersoil** [comment]
> I think I came up with a solution that will work no matter where it's displayed, and it doesn't rely on `dev.size`. First, you generate a plot and save it in high resolution as a jpeg. Then you read the static images, and all issues with scaling are gone.

@nizwant are you able to implement this approach soon? I guess fixing this error is the last element that stops us from releasing a *new package version*

**Comment by nizwant** [comment]
> > I think I came up with a solution that will work no matter where it's displayed, and it doesn't rely on `dev.size`. First, you generate a plot and save it in high resolution as a jpeg. Then you read the static images, and all issues with scaling are gone.
> 
> @nizwant are you able to implement this approach soon? I guess fixing this error is the last element that stops us from releasing a _new package version_

I was testing it yesterday but this approach turned out to be slow, at least on my hardware and R version

**Comment by Fersoil** [comment]
image
image
updated plots

**Review by Fersoil — APPROVED** [review]

**Pull request merged**
